[tool.poetry]
name = "playwright-tests-api-e2e"
version = "0.1.0"
description = "Testes automatizados de API e E2E com Playwright, Pytthon e Cucumber"
authors = ["Julio Parra <julio1652@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.0"
pytest-playwright = "^0.7.2"
playwright = "^1.57.0"
pytest-bdd = "^8.1.0"
python-dotenv = "^1.0.1"
Faker = "^33.1.0"
allure-combine = "^1.0.11"
taskipy = "^1.12.2"
allure-pytest = "^2.15.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
# Configurações padrão do Pytest
addopts = "--alluredir=allure-results --clean-alluredir --verbose -s --strict-markers"
testpaths = ["e2e_tests", "api-tests"]
markers = [
    "web: Testes E2E",
    "api: Testes de API"
]

[tool.taskipy.tasks]
test-api = "pytest -m api"
test-e2e = "pytest -m web --headed --slowmo 500 --tracing=retain-on-failure"
generate = "allure generate allure-results -o allure-report --clean"
combine = "allure-combine allure-report"
report = "task generate && task combine"
run-all-api = "task test-api && task report || task report"
run-all-e2e = "task test-e2e && task report || task report"
test-all = "pytest && task report || task report"
