name: Playwright Tests

on:
  push:

  workflow_dispatch:
    inputs:
      target_env:
        description: 'Qual ambiente testar?'
        required: true
        default: 'qa'
        type: choice
        options:
        - dev
        - qa
        - prd

jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'poetry'

    - name: Install Dependencies
      run: poetry install

    - name: Cache Playwright Browsers
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/poetry.lock') }}

    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: poetry run playwright install --with-deps

    - name: Run Tests
      env:
        BASE_URL_DEV: ${{ secrets.BASE_URL_DEV }}
        BASE_URL_QA: ${{ secrets.BASE_URL_QA }}
        BASE_URL_PRD: ${{ secrets.BASE_URL_PRD }}
        
        API_URL_DEV: ${{ secrets.API_URL_DEV }}
        API_URL_QA: ${{ secrets.API_URL_QA }}
        API_URL_PRD: ${{ secrets.API_URL_PRD }}
        
        API_TOKEN: ${{ secrets.API_TOKEN }}

        GOREST_BASE_URL: ${{ secrets.GOREST_BASE_URL }}
        GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}
      
      run: |
        ENV_NAME="${{ inputs.target_env || 'qa' }}"
        
        echo "Rodando testes no ambiente: $ENV_NAME"
        
        poetry run task test-all --env=$ENV_NAME

    - name: Get Allure History
      uses: actions/checkout@v4
      continue-on-error: true
      if: always()
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: ${{ github.workspace }}/allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history